				
				
				<?php if(COMPONENTE == 'configuracion') $active='active'; else $active='';?>
				
				<ul class="sidebar-group tab-pane <?php echo $active;?>" id="configuracion">
					<li class="navigation-header">Configuración</li>
					<li><a href="<?php echo BASE_URL; ?>configuracion/infoyseo">Info y Seo</a></li>
					<li><a href="<?php echo BASE_URL; ?>configuracion/system">Sistema</a></li>
					<li><a href="<?php echo BASE_URL; ?>configuracion/estructura">Estructura</a></li>
				</ul>
