

<div class="row">
    <!-- Full width table -->
    <div class="col-lg-12">
        <div class="module no-padding">
            <div class="module-content table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        if ($this->_firmantes) {
                            foreach ($this->_firmantes as $firmante) {
                                echo '<tr>';
                                echo '<td>' . $firmante['nombre'] . '</td>';
                                echo '<td>' . $firmante['email'] . '</td>';
                                echo '</tr>';
                            }
                        }
                        ?>
                    </tbody>
                </table>

            </div>
        </div>

    </div>
    <!-- /Full width table -->
</div>


