<!-- Badges -->
    <div class="col-lg-6">

            <div class="module">
                    <div class="module-header"><h4>Sistema de caché</h4></div>
                    <div class="module-content clearfix">

                            <ul class="nav nav-pills nav-stacked" >
                            <?php 
                            if($this->_componentes){
                                    foreach($this->_componentes->component as $componente){
                                            if($componente->hidden == 'true')
                                                    continue;
                                            ?>
                                            <li class="active">
                                            <a>
                                                    <div class="onoff">
                                                            <?php 
                                                            if($componente->enabled == 'true' || !isset($componente->enabled))
                                                                    $switch = 'Off';
                                                            else 
                                                                    $switch = 'On';

                                                            ?>
                                                    </div>
                                                    <?php echo $componente->displayName;?>
                                            </a><br>
                                            </li>
                                            <?php 
                                    }	

                            }?>
                            </ul>

                    </div>
            </div>
    </div>
<!-- /Badges -->