<!-- Content area -->
		<div id="content-wrapper">
			<!-- Site header -->
			<header class="main-header">
				
				<!-- Page title -->
				<h3>
					<a id="show-menu" href="#" class="btn btn-primary"><i class="icon-reorder"></i></a>
					Nueva noticia
				</h3>
				<!-- Profile dropdown -->
				<nav class="user-profile">
					<a href="<?php echo BASE_URL.'login/cerrarsesion' ?>" class="user-dropdown" >
						<span>Cerrar sesión</span>
					</a>
				</nav>
			</header>
			<!-- /Site header -->
			
			<!-- Main Content -->
			<section class="main-content padding">
				
				<div class="row">
					
					<!-- Basic forms -->
					<div class="col-lg-12">
						<div class="module">
							<div class="module-header"><h4></h4></div>
							<div class="module-content">
								<form method="post" action="<?php echo BASE_URL.'noticias/agregar'; ?>" class="form-horizontal" >						
									<div class="form-group">
										<div class="col-lg-12">
											<div class="col-lg-offset-3 col-lg-3">
												<div class="form-group">
													<label for="select1" class="col-lg-4 control-label">Sección</label>
													<div class="col-lg-8">
														<?php 
															Form::select($this->_secciones,'id','seccion','secciones','Sección','form-control');
														?>
													</div>
												</div>
											</div>
											<div class="col-lg-3">
												<div class="form-group">
													<label for="select1" class="col-lg-5 control-label">Firmantes</label>
													<div class="col-lg-7">
														<?php 
															Form::select($this->_firmantes,'id','nombre','firmante','Firmante','form-control');
														?>
													</div>
												</div>											
											</div>
											<div class="col-lg-3">
												<label for="select1" class="col-lg-5 control-label">Orden</label>
												<div class="col-lg-7">
													<input type="number" class="form-control" value="0" name="orden"/>
												</div>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label for="input1" class="col-lg-2 control-label">Título</label>
										<div class="col-lg-10">
											<textarea class="form-control" rows="2" name="titulo"></textarea>
										</div>
									</div>

									<div class="form-group">
										<label for="input2" class="col-lg-2 control-label">Subtítulo</label>
										<div class="col-lg-10">
											<textarea class="form-control" rows="2" name="subtitulo"></textarea>
										</div>
									</div>

									<div class="form-group">
										<label for="input3" class="col-lg-2 control-label">Entradilla</label>
										<div class="col-lg-10">
											<textarea class="form-control" rows="3" name="texto"></textarea>
										</div>
									</div>
									<div class="form-group">
										<label for="input3" class="col-lg-2 control-label">Texto</label>
										<div class="col-lg-10">
											<textarea class="form-control" rows="10" name="texto"></textarea>
										</div>
									</div>
									
									


									<div class="form-group">
										<div class="col-lg-offset-2 col-lg-10">
											<button class="btn btn-primary">Guardar noticia</button>
										</div>
									</div>

								</form>

							</div>
						</div>
					</div>
					<!-- /Basic forms -->
				</div>

			</section>
			<!-- /Main Content -->

		</div>
		<!-- /Content area -->
		<!-- 
		
			<form method="post" action="<?php echo BASE_URL.'noticias/agregar'; ?>">
	<table>
		<tr>
			<td>
				<?php 
				Form::select($this->_firmantes,'id','nombre','firmante','Firmante');
				?>
			</td>
			<td>
			<?php
				Form::select($this->_secciones,'id','seccion','secciones','Sección');
				?>
			</td>
			<td>Orden	
				<input type="text" name="orden"  size="5"  maxlength="9"/>
			</td>
			<td>
				<?php Form::button('Guardar noticia','positive','add'); ?>
				<?php //Form::button('Ampliar noticia','regular','blue'); ?>
				<?php //Form::button('Eliminar noticia','negative','delete'); ?>
	 
			</td>
		</tr>
	</table>
	<h2>Título</h2>	
		<textarea rows="1"  name="titulo"></textarea>
	<h2>Subtítulo</h2>
		<textarea rows="1"  name="subtitulo"></textarea>	
	<h2>Entradilla</h2>
		<textarea rows="4"  name="entradilla"></textarea>
	<h2>Texto</h2>	
		<textarea rows="15"  name="texto"></textarea>
</form>*//Content area -->