				
				
				<?php if(COMPONENTE == 'paginas') $active='active'; else $active='';?>
				<ul class="sidebar-group tab-pane <?php echo $active; ?>" id="paginas">
					<li class="navigation-header">Configuración</li>
					<li><a href="<?php echo BASE_URL; ?>paginas/maquetacion">Maquetación</a></li>
					<li><a href="<?php echo BASE_URL; ?>paginas/listado">Listado</a></li>
					<li><a href="<?php echo BASE_URL; ?>paginas/modulos">Módulos</a></li>
				</ul>

