<!-- Site header -->
			<header class="main-header">
				
				<!-- Page title -->
				<h3>
					<a id="show-menu" href="#" class="btn btn-primary"><i class="icon-reorder"></i></a>
					Listado de secciones
				</h3>
				
				<!-- Profile dropdown -->
				<span class="user-profile">
					<a href="<?php echo BASE_URL.'login/cerrarsesion' ?>" class="user-dropdown" >
						<span>Cerrar sesión</span>
					</a>
				</span>

			</header>
			<!-- /Site header -->
			
			<!-- Main Content -->
			<section class="main-content padding">
				<div class="row">
				<!-- Basic forms -->
					<div class="col-lg-8">
						<div class="module">
							<div class="module-header"></div>
							<div class="module-content">
								<form name="firmanteForm2" method="post" action="<?php echo BASE_URL_COM.'agregar'; ?>" class="form-horizontal">
									<div class="form-group">
										<label for="input1" class="col-lg-2 control-label">Sección</label>
										<div class="col-lg-10">
											<input type="text" class="form-control" name="seccion" placeholder="Titular de la sección" />
										</div>
									</div>
									<div class="form-group">
										<div class="col-lg-offset-3 col-lg-10">
											<button type="submit" class="btn btn-success">Agregar sección</button>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
					<!-- /Basic forms -->
				</div>
				<div class="row">
					
					<!-- Full width table -->
					<div class="col-lg-12">
						<form name="firmantesForm" method="post" action="<?php echo BASE_URL_COM.'eliminar'; ?>">
							<div class="module no-padding">
								<div class="module-content table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th></th>
												<th>ID</th>
												<th>Sección</th>
											</tr>
										</thead>
										<tbody>
											<?php if($this->_secciones){
												foreach ($this->_secciones as $seccion){
													echo '<tr>';
													echo '<td style="width:15px;"><input name="secciones[]" type="checkbox" id="checkbox[]" value="'.$seccion['id'].'"></td>';
													echo '<td style="width:25px;">'.$seccion['id'].'</td>';
													echo '<td>'.$seccion['seccion'].'</td>';
													echo '</tr>';
												}
											}?>
										</tbody>
									</table>
									
								</div>
							</div>
							<?php if($this->_secciones){?> 
								<button type="submit" class="btn btn-danger">Eliminar secciones seleccionadas</button>
							<?php } ?>
						</form>
					</div>
					<!-- /Full width table -->
				</div>
			</section>
			<!-- /Main Content -->

		</div>
		<!-- /Content area -->


<!-- 
<form method="post" action="<?php echo BASE_URL.'secciones/agregar'; ?>">
<h2>Agregar una nueva sección:</h2>
	<textarea rows="1"  name="seccion" style="width:50%;"></textarea>	
	<p></p>
	<?php Form::button('Agregar','positive','add'); ?>
	<?php Form::button('Eliminar noticias seleccionadas','negative','delete'); ?>
	<p></p>
</form>
<form method="post" action="<?php echo BASE_URL.'secciones/eliminar'; ?>">
<table>
	<tr>
	    <th></th>
		<th>ID</th>
		<th>SECCIÓN</th>
	</tr>
		<?php if($this->_secciones){
			foreach ($this->_secciones as $seccion){
				echo '<tr>';
				echo '<td style="width:15px;"><input name="secciones[]" type="checkbox" id="checkbox[]" value="'.$seccion['id'].'"></td>';
				echo '<td style="width:25px;">'.$seccion['id'].'</td>';
				echo '<td>'.$seccion['seccion'].'</td>';
				echo '</tr>';
			}
		}?>
</table>
</form> -->