<!-- Site header -->
			<header class="main-header">
				
				<!-- Page title -->
				<h3>
					<a id="show-menu" href="#" class="btn btn-primary"><i class="icon-reorder"></i></a>
					Listado de páginas
				</h3>
				
				<!-- Profile dropdown -->
				<span class="user-profile">
					<a href="<?php echo BASE_URL.'login/cerrarsesion' ?>" class="user-dropdown" >
						<span>Cerrar sesión</span>
					</a>
				</span>

			</header>
			<!-- /Site header -->
			
			<!-- Main Content -->
			<section class="main-content padding">
				<div class="row">
				<!-- Basic forms -->
					<div class="col-lg-6">
						<div class="module">
							<div class="module-header"></div>
							<div class="module-content">
								<form name="firmanteForm2" method="post" action="<?php echo BASE_URL_COM.'paginas/agregar'; ?>" class="form-horizontal">
									<div class="form-group">
										<label for="input1" class="col-lg-2 control-label">Título</label>
										<div class="col-lg-9">
											<input type="text" class="form-control" name="titulo" />
										</div>
									</div>
									<div class="form-group">
										<label for="input1" class="col-lg-2 control-label">Descripción</label>
										<div class="col-lg-9">
                                                                                    <textarea class="form-control" name="descripcion"></textarea>
										</div>
									</div>
                                                                    	<div class="form-group">
										<div class="col-lg-offset-2 col-lg-10">
											<button type="submit" class="btn btn-success">Agregar nueva página</button>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
					<!-- /Basic forms -->
				</div>
				<div class="row">
					
					<!-- Full width table -->
					<div class="col-lg-12">
						<form name="firmantesForm" method="post" action="<?php echo BASE_URL_COM.'paginas/eliminar'; ?>">
							<div class="module no-padding">
								<div class="module-content table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th></th>
												<th>ID</th>
												<th>Titulo</th>
												<th>Descripción</th>
											</tr>
										</thead>
										<tbody>
											<?php if($this->_paginas){
												foreach ($this->_paginas as $pagina){
													echo '<tr>';
													echo '<td style="width:15px;"><input name="paginas[]" type="checkbox" id="checkbox[]" value="'.$pagina['id'].'"></td>';
													echo '<td style="width:25px;">'.$pagina['id'].'</td>';
													echo '<td>'.$pagina['titulo'].'</td>';
													echo '<td>'.$pagina['descripcion'].'</td>';
													echo '</tr>';
												}
											}?>
										</tbody>
									</table>
									
								</div>
							</div>
							<?php if($this->_paginas){?> 
								<button type="submit" class="btn btn-danger">Eliminar páginas seleccionadas</button>
							<?php } ?>
						</form>
					</div>
					<!-- /Full width table -->
				</div>
			</section>
			<!-- /Main Content -->

		</div>
		<!-- /Content area -->


