<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Login CMS.UM</title>
    <meta name="description" content="CMS.UM">
    <meta name="author" content="Borja Abad">
	<?php  Media::js();  ?>
	<?php  Media::css();  ?>
  </head>
	<body>
	<div class="login_container">
      <div class="login">
		<form method="post" action="<?php echo BASE_URL.'login/validar/'; ?>" >
        <h2>Login</h2>
        <input type="text" name="user" placeholder="User">
        <input type="password" name="pass" placeholder="Password">
        <button type="submit">Sign in</button>
      </form>
	  </div>
    </div>
        <?php Alertify::mostrarMensajes();?>
  </body>
</html>