
		
		<!-- Content area -->
		<div id="content-wrapper">
			
			<!-- Site header -->
			<header class="main-header">
				
				<!-- Page title -->
				<h3>
					<a id="show-menu" href="#" class="btn btn-primary"><i class="icon-reorder"></i></a>
					DASHBOARD
				</h3>
				
				<!-- Profile dropdown -->
				<nav class="user-profile">
					<a href="#" class="user-dropdown" data-toggle="dropdown">
						<img src="img/avatar.jpg" alt="avatar" />
						<span>Adam Tate</span>
						<i class="icon-caret-down"></i>
					</a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="#">Profile</a></li>
						<li><a href="#">Messages</a></li>
						<li><a href="#">Tasks</a></li>
						<li><a href="error.html">Show error</a></li>
						<li><a href="login.html">Logout</a></li>
					</ul>
				</nav>

			</header>
			<!-- /Site header -->
			
			<!-- Main Content -->
			<section class="main-content padding">

			MAIN

		</div>
		<!-- /Content area -->