<?php
$modulos = $this->_modulos;
$modulos = $modulos->asXML();

$plantilla = BASE_URL.'components/paginas/views/maquetacion/layoutit.php';

?>

<iframe name="Stack" 
        frameborder="0" 
        scrolling="yes" 
        id="layoutit" 
        width="100%" 
        height="800px" 
        onload='javascript:resizeIframe();'
        overflow-x="hidden"
        src="<?php echo $plantilla; ?>" 
        />