<!-- Content area -->
<div id="content-wrapper">
    <header class="main-header">
        
        <!-- Page title -->
        <h3>
            <a id="show-menu" href="#" class="btn btn-primary"><i class="icon-reorder"></i></a>
            Información y SEO
        </h3>
            
        <!-- Profile dropdown -->
        <span class="user-profile">
            <a href="<?php echo BASE_URL.'login/cerrarsesion' ?>" class="user-dropdown" >
                <span>Cerrar sesión</span>
            </a>
        </span>
            
    </header>
    <!-- /Site header -->
        
    <!-- Main Content -->
    <section class="main-content padding">
        <div class="row">
            
            <!-- Basic forms -->
            <div class="col-lg-12">
                <div class="module">
                    <div class="module-header"><h4></h4></div>
                    <div class="module-content">
                        
                        <form action="" class="form-horizontal" method="POST">
                            <div class="form-group">
                                <label for="input1" class="col-lg-2 control-label">Título de la publicación</label>
                                <div class="col-lg-10">
                                    <input type="text" class="form-control" name="titulo" value="<?php echo TITULO; ?>" />
                                </div>
                            </div>
                                
                            <div class="form-group">
                                <label for="input2" class="col-lg-2 control-label">Descripción</label>
                                <div class="col-lg-10">
                                    <textarea class="form-control" rows="3" name="descripcion" maxlength="2000"><?php echo DESCRIPCION; ?></textarea>
                                </div>
                            </div>
                                
                            <div class="form-group">
                                <label for="input3" class="col-lg-2 control-label">Keywords</label>
                                <div class="col-lg-10">
                                    <textarea class="form-control" rows="3" name="keywords"><?php echo KEYWORDS; ?></textarea>
                                </div>
                            </div>
 
                            <div class="form-group">
                                <label for="input3" class="col-lg-2 control-label">Dirección de la web</label>
                                <div class="col-lg-10">
                                    <input type="url" class="form-control" name="url" value="<?php echo URL; ?>" />
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-primary">Guardar cambios</button>
                                    <button class="btn btn-default" name="cancel">Cancel</button>
                                </div>
                            </div>
                        </form>
                            
                    </div>
                </div>
            </div>
            <!-- /Basic forms -->
                
        </div>
    </section>
    <!-- /Main Content -->
</div>
<!-- /Content area -->