<!-- Content area -->
<div id="content-wrapper">
    <!-- Site header -->
    <header class="main-header">
        
        <!-- Page title -->
        <h3>
            <a id="show-menu" href="#" class="btn btn-primary"><i class="icon-reorder"></i></a>
            <span id="nuevaNoticia"><?php echo $this->_modulo['nombre']; ?></span>
        </h3>
        <!-- Profile dropdown -->
        <span class="user-profile">
            <a href="<?php echo BASE_URL.'login/cerrarsesion' ?>" class="user-dropdown" >
                <span>Cerrar sesión</span>
            </a>
        </span>
    </header>
    <!-- /Site header -->
    
    <!-- Main Content -->
    <section class="main-content padding">
        
        <div class="row">
            
            <!-- Basic forms -->
            <div class="col-lg-12">
                <div class="module">
                    <div class="module-header"><h4></h4></div>
                    <div class="module-content">
                       <?php echo '<form method="post" action="'.BASE_URL_COM.'modulos/guardar" class="form-horizontal" >'; ?>
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <input type="hidden" name="idModulo" value="<?php echo $this->_modulo['id']; ?>">
                                    <textarea class="form-control ckeditor" id="texto"  rows="10" name="content"><?php echo $this->_modulo['content']; ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-primary" name="guardar">Guardar módulo</button>
                                </div>
                            </div>
                        </form>                       
                    </div>
                </div>
                <!-- /Basic forms -->
            </div>
            <div class="col-lg-12">
                <div class="module">
                    <div class="module-content clearfix">
                        <h4>Para la creación de módulos puede usar cualquier recurso web HTML/CSS/Javasript, algunas páginas interesantes donde obtener una base a modelar son:</h4>
                        <ul>
                            <li>Generación de elementos diversos:<a href="http://bootsnipp.com/">http://bootsnipp.com/</a></li>
                            <li>Generación de formularios:<a href="http://bootsnipp.com/">http://bootsnipp.com/</a></li>
                            <li>Generación de elementos básicos:<a href="http://getbootstrap.com/components/">http://getbootstrap.com/components/</a></li>
                        </ul>
                    </div>
                </div>
            </div>
    </section>
    <!-- /Main Content -->
    
</div>
<!-- /Content area -->

<script>

CKEDITOR.replace( 'texto',  {
    uiColor: '#9AB8F3',
    height: '500px',
    toolbar: [
		{ name: 'document', items: [ 'Source' ] },	// Defines toolbar group with name (used to create voice label) and items in 3 subgroups.
		[ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ],			// Defines toolbar group without name.
		{ name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline' ] },
                { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] },
                { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
                { name: 'insert', items: [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] },
                { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },
                { name: 'colors', items: [ 'TextColor', 'BGColor' ] },
                { name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] },
	]
});

</script>
