	<link rel="StyleSheet" href="<?php echo BASE_URL.'public/css/alertify.core.css';?>" type="text/css">
	<link rel="StyleSheet" href="<?php echo BASE_URL.'public/css/alertify.default.css';?>" id="toggleCSS" type="text/css">
	<link rel="StyleSheet" href="<?php echo BASE_URL.'public/css/bootstrap.min.css';?>" type="text/css">
	<link rel="StyleSheet" href="<?php echo BASE_URL.'public/css/css.css'; ?>" type="text/css">
	<link rel="StyleSheet" href="<?php echo BASE_URL.'public/css/kato.css'; ?>" type="text/css">
	<link rel="StyleSheet" href="<?php echo BASE_URL.'public/css/fonts.css';?>" id="toggleCSS" type="text/css">

