    
    
        <script type="text/javascript" src="<?php echo BASE_URL;?>public/js/alertify.min.js"></script>
        <script type="text/javascript" src="<?php echo BASE_URL;?>public/js/jquery.js"></script>
        <!-- Raphael Framework -->
        <script src="<?php echo BASE_URL;?>/public/js/raphael.min.js"></script>
        <!-- Small Graphs -->
        <script src="<?php echo BASE_URL;?>/public/js/sparklines.min.js"></script>
        <!-- Knobs -->
        <script src="<?php echo BASE_URL;?>/public/js/knob.js"></script>
        <!-- Bootstrap Javascript -->
        <script src="<?php echo BASE_URL;?>/public/js/bootstrap.min.js"></script>
        <!-- Kato Javascript --> 
        <script src="<?php echo BASE_URL;?>/public/js/theme.js"></script>