				
				
				<?php if(COMPONENTE == 'noticias') $active='active'; else $active='';?>
				
				<ul class="sidebar-group tab-pane <?php echo $active;?>" id="noticias">
					<li class="navigation-header">Noticias</li>
					<li><a href="<?php echo BASE_URL; ?>noticias/nueva">Nueva</a></li>
					<li><a href="<?php echo BASE_URL; ?>noticias/listado">Listado</a></li>
					<li><a href="<?php echo BASE_URL; ?>noticias/firmantes">Firmantes</a></li>
				</ul>
