    <div class="row otrasnoticias">
            <!-- Full width table -->
            <div class="col-lg-12">
                            <div class="module no-padding">
                               <?php if($this->_noticias)echo' <h4>Más artículos</h4>';?>
                                    <div class="module-content table-responsive">
                                        <tbody>
                                                <?php if($this->_noticias){
                                                        $aux = false;$ultima=false;
                                                        foreach ($this->_noticias as $noticia){
                                                                  if(isset($noticia['titulo'])){
                                                                      
                                                                      if(!$aux){
                                                                       if($ultima != $noticia['seccion'])
                                                                        echo '<a href="'.BASE_URL.'seccion/'.$noticia['id_seccion'].'/'.$this->getUrlFriendlyString($noticia['seccion']).'">'
                                                                        . '<div class="otrasnoticias seccion">'.$noticia['seccion'].'</div>'
                                                                            . '</a>';
                                                                        $aux = false;
                                                                        $ultima = $noticia['seccion'];
                                                                      }else{
                                                                          $aux = $noticia['seccion'];
                                                                         // $ultima='';
                                                                      }
                                                                      echo '<a href="'.BASE_URL.'noticia/'.$noticia['id'].'/'.$this->getUrlFriendlyString($noticia['titulo']).'">'
                                                                      . '<div class="otrasnoticias titulo">'.$noticia['titulo'].'</div>'
                                                                          . '</a>';
                                                                      
                                                                  }
                                                        }
                                                }?>

                                        </tbody>
                                    </div>
                            </div>
            </div>
            <!-- /Full width table -->
    </div>