<!-- Badges -->
<div class="col-lg-5" style="min-width: 350px;" >
    <div class="module module-red">
        <div class="module-header"><h4>Zonas del sitio web</h4></div>
        <div class="module-content clearfix">
            
            <ul class="nav nav-pills nav-stacked" >
                <table id="visor_estructura" class="table-responsive">
                    <tr>
                        <td id="MSCFC" colspan="5" class="m">TOP 2</td>
                    </tr>
                    <tr>
                        <td id="MSC" colspan="4" class="m">TOP 1</td>		
                        <td id="MDFC" rowspan="10" class="m">RIGHT RIGHT</td>
                    </tr>
                    <tr>
                        <td id="C" colspan="4" style="color:#ce4724;border:1px solid #ce4724;">Cabecera <span id="MDC" class="m" style="color:white"> CENTER IN </span></td>
                    </tr>
                    <tr>
                        <td id="MBC" colspan="4" class="m">TOP BOTTOM</td>
                    </tr>
                    <tr>
                        <td id="MVI" rowspan="6" class="m">LEFT</td>
                        <td id="MSN" colspan="2" class="m">CENTER TOP</td>
                        <td id="MVD" rowspan="6" class="m">RIGHT</td>
                    </tr>
                    <tr>
                        <td id="NP" colspan="2">CENTER</td>
                    </tr>
                    <tr>
                        <td id="MSNC" class="m">CENTER LEFT</td>
                        <td id="MTC" class="m">CENTER RIGHT</td>
                    </tr>
                    <tr>
                        <td id="NC">LEFT MAIN</td>
                        <td id="TC" rowspan="2">RIGHT MAIN</td>
                    </tr>
                    <tr>
                        <td id="MFIN1" class="m">LEFT MAIN BOTTOM</td>
                    </tr>
                    <tr>
                        <td id="MFIN2" class="m" colspan="2">CENTER BOTTOM</td>
                    </tr>
                    <tr>
                        <td id="MFIN3" class="m" colspan="4">BOTTOM</td>
                    </tr>
                   <tr>
                        <td id="C" colspan="5" style="color:#ce4724; border:1px solid #ce4724;">Pie</td>
                    </tr>                    
                </table>
            </ul>
            
        </div>
    </div>
</div>
<!-- /Badges -->
