<!-- Badges -->
<div class="col-lg-7">
    <div class="module">
        <div class="module-header"><h4>Información</h4></div>
        <div class="module-content clearfix">
            
            <ul class="nav nav-pills nav-stacked" >
                <li>
                    <p>Estas posiciones las encontrará por todo el CMS, es el lugar donde fijamos nuestros <b>módulos</b>.</p>                    
                </li>
                <li>
                            <h3>Genere sus propias plantillas</h3>
                            <p>
                                Respetando esta posiciones básicas, podrá generar externamente sus plantillas, diseños, archivos en cascada, etc. Queda así separada totalmente la presentación de, el negocio.
                            </p>
                            <h3>Cambie el layout con una sola variable</h3>                            
                            <p>
                                Los diseños se pueden hacer en paralelo, y cambiar según la necesidad al vuelo.
                            </p>
                            <h3>Las cosas claras</h3>                            
                            <p>
                                Tenga un inventario de los productos de su web de una manera sencilla e intuitiva. Use el <b>gestor de módulos</b> con su funcionalidad <i>Drag&Drop</i> para organizar el contenido a su gusto con total libertad, de manera muy intuitiva y poderosa.
                            </p>
                </li>
            </ul>
            
        </div>
    </div>
</div>
<!-- /Badges -->
