<a href="<?php echo BASE_URL; ?>">
	<div id="menuItem">
		 << Noticias
	</div>
</a>
<a href="<?php echo BASE_URL_COM.'nueva'; ?>">
	<div id="menuItem">
		Nueva
	</div>
</a>
<a href="<?php echo BASE_URL_COM.'listado'; ?>">
	<div id="menuItem">
		Listado
	</div>
</a>
<a href="<?php echo BASE_URL_COM.'firmantes'; ?>">
	<div id="menuItem">
		Firmantes
	</div>
</a>
<a href="<?php echo BASE_URL_COM.'estilos'; ?>">
	<div id="menuItem">
		Estilos
	</div>
</a>