<table>
	<tr>
		<td>
			<div class="wrap"><a href="<?php echo BASE_URL_COM.'nueva';?>">Nueva</a></div>
		</td>
		<td>
			<div class="wrap"><a href="<?php echo BASE_URL_COM.'editar';?>">Editar</a></div>
		</td>
		<td>
			<div class="wrap"><a href="<?php echo BASE_URL_COM.'firmantes';?>">Firmantes</a></div>
		</td>
		<td>
			<div class="wrap"><a href="<?php echo BASE_URL_COM.'estilos';?>">Estilos</a></div>
		</td>
	</tr>
</table>